### ISSUE TITLE
Slicer Advanced Options

### ISSUE THREAD

**Issue by thenineteen** [fepegar/EpilepsySemiology#3]
is there a way to add an "advanced settings" tab on slicer so we can play around with the settings on the GUI? e.g. have a methods section where we can chose between

'min_max' (minmaxscaler)
'QuantileTransformer' OR 'non-linear'
'chi2' (chi-squared distribution)

which then changes the default method keyword arguments in the functions:

pivot_result_to_pixel_intensities
lateralisation_to_pixel_intensities

(there will be other advanced settings which tweaking to see how it affects visualisation would be useful e.g. function calls to "scale_factor" , "quantiles" "use_semiology_dictinoary" keyword arguments)

all of these could/should be run from https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/scripts/slicer_run_query_semiology_lateralisation.py

**Comment by fepegar** [comment]
Yes, we'll add this once it's working on everyone's computers.
