### ISSUE TITLE
slicer initialisation

### ISSUE THREAD

**Issue by thenineteen** [fepegar/EpilepsySemiology#6]
in order to reduce run time (see [issue](https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/5))  a new [script](https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/scripts/slicer_initialisation.py) added to SVT to run as slicer loads. Will then have to store the df from this script for the user query to work.

**Comment by fepegar** [comment]
If it's Slicer who should run this, you don't need to add a new file for it. We should start using pull requests for new changes, instead of committing directly. Everything is breaking because of this.

**Comment by fepegar** [comment]
Also, let's stop creating issues on this repository.
